apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-maven
spec:
  description: |
    This pipeline clones a Git repository containing a Maven projects and builds it
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from
  workspaces:
    - name: shared-data
      description: |
        This workspace contains the cloned repo
  tasks:
    - name: checkout
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: ${params.repo-url}
    - name: run-tests
      params:
        - name: GOALS
          value:
            - test
      runAfter:
        - checkout
      taskRef:
        name: maven
      workspaces:
        - name: source
          workspace: shared-data
        - name: maven-settings
          workspace: shared-data
    - name: get-version
      runAfter:
        - run-tests
      taskRef:
        name: maven-get-project-version
      workspaces:
        - name: source
          workspace: shared-data
