---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-application
  labels:
    app:  my-application
spec:
  selector:
    matchLabels:
      app: my-application
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  my-application
    spec:
      containers:
      - name:  my-app
        image: docker.io/library/nginx:1.25.2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
---

